{% set version = "2.9.2" %}

package:
  name: pdal
  version: {{ version }}

source:
  url: https://github.com/PDAL/PDAL/releases/download/{{ version }}/PDAL-{{ version }}-src.tar.bz2
  sha256: a74bbc7f4e4f709ed589dbbb851926a63c391c974e3fc40a4c3ff34f7923021b

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('pdal', max_pin='x.x') }}

requirements:
  build:
  host:
  run:
    - libpdal {{ version }}
    - python-pdal

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Data Abstraction Library (PDAL) meta package
  description: Point cloud data processing library meta package
  doc_url: https://pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
